config:
  target: "http://localhost:8888"
  phases:
    - duration: 60
      arrivalRate: 5
      rampTo: 20
      name: "Ramp up load"
    - duration: 120
      arrivalRate: 20
      name: "Sustained load"
  defaults:
    headers:
      User-Agent: "Artillery"
  plugins:
    metrics-by-endpoint: {}
  ensure:
    p95: 500
    maxErrorRate: 1
  reporting:
    - json
    - html

scenarios:
  - name: "Get archetype config"
    flow:
      - get:
          url: "/archetypes/node-fullstack"
          expect:
            - statusCode: 200
      - think: 1
  - name: "Get rule"
    flow:
      - get:
          url: "/archetypes/node-fullstack/rules/sensitiveLogging-iterative"
          expect:
            - statusCode: 200
      - think: 1
  - name: "Send telemetry"
    flow:
      - post:
          url: "/telemetry"
          json:
            eventType: "testEvent"
            metadata:
              archetype: "node-fullstack"
              repoPath: "/test/repo"
              testData: "performance test"
            timestamp: "{{ $isoTimestamp }}"
          expect:
            - statusCode: 200
      - think: 1
