name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install

    - name: Build all packages
      run: npx nx run-many --target=build --all

    - name: Install xvfb for VSCode extension tests
      run: sudo apt-get update && sudo apt-get install -y xvfb

    - name: Run tests
      run: npx nx run-many --target=test --all
      env:
        DISPLAY: ':99.0'

    - name: Run fixture validation
      run: npx nx run fixtures:test

  global-install-test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install

    - name: Build all packages
      run: npx nx run-many --target=build --all

    - name: Run local package global install test
      run: npx nx run cli:global:test:local


