name: Code review
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review
    steps:
      - name: GenAI Code Review
        uses: cirolini/genai-code-review@v2
        with:
          entrypoint: "python /app/src/main.py"
          openai_api_key: ${{ secrets.OPENAI_AI_KEY }}
          github_token: ${{ secrets.GH_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_model: "gpt-4-turbo" # optional
          openai_temperature: 0.5 # optional
          openai_max_tokens: 2048 # optional
          mode: files # files or patch
          language: en # optional, default is 'en'
          custom_prompt: "" # optional
