name: VSCode Extension CI

on:
  pull_request:
    branches: [master]
    paths:
      - 'packages/x-fidelity-cli/**'
      - 'packages/x-fidelity-vscode/**'
      - 'packages/x-fidelity-core/**'
      - 'packages/x-fidelity-types/**'
      - 'packages/x-fidelity-plugins/**'
      - '.github/workflows/vscode-extension-ci.yml'
  push:
    branches:
      - master
      - 'feature/**'
    paths:
      - 'packages/x-fidelity-cli/**'
      - 'packages/x-fidelity-vscode/**'
      - 'packages/x-fidelity-core/**'
      - 'packages/x-fidelity-types/**'
      - 'packages/x-fidelity-plugins/**'
      - '.github/workflows/vscode-extension-ci.yml'
  workflow_dispatch: # Allow manual trigger

jobs:
  test-extension:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    strategy:
      matrix:
        vscode-version: ['stable']
        node-version: ['22.x']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build all packages
        run: yarn build
        
      - name: Setup Xvfb for headless testing
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          
      - name: Lint extension
        run: yarn workspace x-fidelity-vscode lint
          
      - name: Type check extension
        run: yarn workspace x-fidelity-vscode check-types
          
      - name: Build VSCode extension
        run: yarn workspace x-fidelity-vscode build
          
      - name: Run unit tests
        run: xvfb-run -a yarn workspace x-fidelity-vscode test:unit
          
      - name: Run integration tests
        run: xvfb-run -a yarn workspace x-fidelity-vscode test:integration
          
      - name: Package extension
        run: yarn workspace x-fidelity-vscode package
          
      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension-${{ matrix.vscode-version }}-node-${{ matrix.node-version }}
          path: packages/x-fidelity-vscode/*.vsix
          retention-days: 7
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.vscode-version }}-node-${{ matrix.node-version }}
          path: |
            packages/x-fidelity-vscode/.vscode-test/
            packages/x-fidelity-vscode/test-results/
          retention-days: 7
          
  publish-check:
    runs-on: ubuntu-latest
    needs: [test-extension]
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'publish-extension')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build all packages
        run: yarn build
        
      - name: Build and package extension
        run: |
          yarn workspace x-fidelity-vscode build
          yarn workspace x-fidelity-vscode package
          
      - name: Verify extension package
        run: |
          cd packages/x-fidelity-vscode
          node scripts/verify-extension.js
          
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-release-candidate
          path: packages/x-fidelity-vscode/*.vsix
          retention-days: 30 